
- name: Create a snapshot of VMWare VM
  hosts: localhost
  gather_facts: no

  vars_files:
    - vars-development.yaml
    - secrets.yaml
  vars:
    snapshot_description: "Snapshot before OS patch."

  tasks:

    - name: Get current date formatted for OS Update
      command: date +"OS-Update-Q%q/%Y"
      register: os_update_date

    - name: Create a snapshot
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        folder: "{{ vm_folder }}"
          #name: "{{ vm_name }}"
        name: "{{ hostvars[item].vm_name }}"
        state: present
        snapshot_name: "{{ os_update_date.stdout }}"
        description: "{{ snapshot_description }}"
        memory_dump: yes
        quiesce: no
      delegate_to: localhost
      loop: "{{ groups['all'] }}"
